CREATE DATABASE DB_ECOMMERCE;

USE DB_ECOMMERCE;

CREATE TABLE TB_ECOMMERCE (
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
CATEGORIA VARCHAR(255),
MARCA VARCHAR(255),
MADEIN VARCHAR(255),
VALOR INT,
PRIMARY KEY (ID)
);

SELECT * FROM TB_ECOMMERCE;

INSERT INTO TB_ECOMMERCE (NOME,CATEGORIA,MARCA,MADEIN,VALOR) VALUE (
'IPHONE 13',
'Celular',
'APPLE',
'CHINA',
13000
);

INSERT INTO TB_ECOMMERCE (NOME,CATEGORIA,MARCA,MADEIN,VALOR) VALUE (
'MI9',
'Celular',
'XIAOMI',
'TAILÂNDIA',
2500
);

INSERT INTO TB_ECOMMERCE (NOME,CATEGORIA,MARCA,MADEIN,VALOR) VALUE (
'FONE DE OUVIDOS',
'Fones/Headphones',
'MULTILASER',
'BRASIL',
100
);

INSERT INTO TB_ECOMMERCE (NOME,CATEGORIA,MARCA,MADEIN,VALOR) VALUE (
'TECLADO',
'Computação',
'RAZER',
'JAPAO',
400
);

INSERT INTO TB_ECOMMERCE (NOME,CATEGORIA,MARCA,MADEIN,VALOR) VALUE (
'XBOX S',
'Video Games',
'MICROSOFT',
'CHINA',
2000
);

INSERT INTO TB_ECOMMERCE (NOME,CATEGORIA,MARCA,MADEIN,VALOR) VALUE (
'PLAYSTATION 5',
'Video Games',
'SONY',
'JAPAO',
5000
);

INSERT INTO TB_ECOMMERCE (NOME,CATEGORIA,MARCA,MADEIN,VALOR) VALUE (
'PROCESSADOR I7',
'Computação',
'INTEL',
'CHINA',
5000
);

INSERT INTO TB_ECOMMERCE (NOME,CATEGORIA,MARCA,MADEIN,VALOR) VALUE (
'THE LAST OF US',
'Video Game',
'NAUGHTY DOG',
'USA',
150
);

SELECT * FROM TB_ECOMMERCE WHERE VALOR > 500;
SELECT * FROM TB_ECOMMERCE WHERE VALOR < 500;

UPDATE TB_ECOMMERCE SET VALOR = 100 WHERE ID = 8;