CREATE DATABASE DB_ESCOLA;

USE DB_ESCOLA;

CREATE TABLE TB_ESCOLA(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
GENERO VARCHAR(255),
MATERIA VARCHAR(255),
IDADE INT,
NOTA DOUBLE,
PRIMARY KEY (ID)
);

SELECT * FROM TB_ESCOLA;

INSERT INTO TB_ESCOLA (NOME,GENERO,MATERIA,IDADE,NOTA) VALUE (
'JOSE',
'MASCULINO',
'PORTUGUES',
13,
7.5
);

INSERT INTO TB_ESCOLA (NOME,GENERO,MATERIA,IDADE,NOTA) VALUE (
'MARIA',
'FEMININO',
'INGLES',
15,
5.0
);

INSERT INTO TB_ESCOLA (NOME,GENERO,MATERIA,IDADE,NOTA) VALUE (
'CLAUDIO',
'MASCULINO',
'MATEMATICA',
11,
6.0
);

INSERT INTO TB_ESCOLA (NOME,GENERO,MATERIA,IDADE,NOTA) VALUE (
'MARINA',
'FEMININO',
'CIENCIAS',
10,
10.0
);

INSERT INTO TB_ESCOLA (NOME,GENERO,MATERIA,IDADE,NOTA) VALUE (
'ABEL',
'MASCULINO',
'ED FISICA',
17,
10.0
);

INSERT INTO TB_ESCOLA (NOME,GENERO,MATERIA,IDADE,NOTA) VALUE (
'FELIPE',
'MASCULINO',
'FISICA',
15,
3.0
);

INSERT INTO TB_ESCOLA (NOME,GENERO,MATERIA,IDADE,NOTA) VALUE (
'ELLEN',
'FEMININO',
'LITERATURA',
16,
9.0
);

INSERT INTO TB_ESCOLA (NOME,GENERO,MATERIA,IDADE,NOTA) VALUE (
'CAROLINE',
'FEMININO',
'PORTUGUES',
16,
7.0
);

SELECT * FROM TB_ESCOLA WHERE NOTA > 7.0;
SELECT * FROM TB_ESCOLA WHERE NOTA < 7.0;

UPDATE TB_ESCOLA SET NOTA = 10.0 WHERE ID = 7; 