CREATE DATABASE DB_GENERATION_GAME_ONLINE;

USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES(
ID BIGINT AUTO_INCREMENT,
ARMA VARCHAR(100),
RACA VARCHAR(100),
PRIMARY KEY (ID)
);

CREATE TABLE TB_PERSONAGENS(
ID BIGINT AUTO_INCREMENT,
HP INT,
ATK INT,
DEF INT,
NICKNAME VARCHAR(100),
PRIMARY KEY (ID),
FK_CLASSES BIGINT,
FOREIGN KEY(FK_CLASSES) REFERENCES TB_CLASSES(ID)
);

SELECT * FROM TB_CLASSES;
SELECT * FROM TB_PERSONAGENS;

INSERT INTO TB_CLASSES (ARMA,RACA) VALUES ( /*Adicionado 5 registros na tabela nessa mesma linha*/
'Arco',
'Arqueiro'
);

INSERT INTO TB_PERSONAGENS(HP,ATK,DEF,NICKNAME,FK_CLASSES) VALUES ( /* Adicionado 8 registros na tabela nessa linha */
1000,
2500,
3000,
'BOSS',
3
);

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_CLASSES.ID = TB_PERSONAGENS.FK_CLASSES;
SELECT * FROM TB_PERSONAGENS WHERE ATK > 2000;
SELECT * FROM TB_PERSONAGENS WHERE DEF BETWEEN 1000 AND 2000;
SELECT NICKNAME FROM TB_PERSONAGENS WHERE NICKNAME LIKE '%c%';
SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_CLASSES.ID = TB_PERSONAGENS.FK_CLASSES WHERE TB_CLASSES.RACA = 'Anão';



