CREATE DATABASE DB_PIZARRIA_LEGAL;

USE DB_PIZARRIA_LEGAL;

CREATE TABLE TB_CATEGORIAS (
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR(50),
TAMANHO VARCHAR(50),
PRIMARY KEY (ID)
);

CREATE TABLE TB_PIZZAS (
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(50),
INGREDIENTE1 VARCHAR(50),
INGREDIENTE2 VARCHAR(50),
VALOR DOUBLE,
PRIMARY KEY (ID),
FK_CATEGORIAS BIGINT,
FOREIGN KEY (FK_CATEGORIAS) REFERENCES TB_CATEGORIAS (ID)
);

SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_PIZZAS;

INSERT INTO TB_CATEGORIAS (TAMANHO, TIPO) VALUES ( /* Foi inserido 4 valores na tabela */
'Broto',
'Salgada'
); /* 1 GD 2BD - 3 GS 4BS*/

INSERT INTO TB_PIZZAS (NOME, INGREDIENTE1, INGREDIENTE2, VALOR, FK_CATEGORIAS) VALUES ( /* Foi inserido 8 valores na tabela*/
'Peruana',
'Atum',
'Cebola',
40.00,
3
);

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.FK_CATEGORIAS;

SELECT * FROM TB_PIZZAS WHERE VALOR > 45;
SELECT * FROM TB_PIZZAS WHERE VALOR BETWEEN 50 AND 100;
SELECT NOME FROM TB_PIZZAS WHERE NOME LIKE '%m%';
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.FK_CATEGORIAS WHERE TB_CATEGORIAS.TIPO = 'Doce';










