CREATE DATABASE DB_FARMACIA_BEM_ESTAR;

USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR(55),
CATEGORIA VARCHAR(100),
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
TARJA VARCHAR(55),
ANO_VALIDADE INT,
VALOR DOUBLE,
PRIMARY KEY (ID),
FK_CATEGORIAS BIGINT,
FOREIGN KEY (FK_CATEGORIAS) REFERENCES TB_CATEGORIAS (ID)
);

SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_CATEGORIAS (TIPO,CATEGORIA) VALUES ( /*1*/
'Original',
'Analgésico'
);
INSERT INTO TB_CATEGORIAS (TIPO,CATEGORIA) VALUES ( /*2*/
'Original',
'Anti-inflamatório'
);
INSERT INTO TB_CATEGORIAS (TIPO,CATEGORIA) VALUES ( /*3*/
'Original',
'Antibiótico'
);
INSERT INTO TB_CATEGORIAS (TIPO,CATEGORIA) VALUES ( /*4*/
'Generico',
'Analgésico'
);
INSERT INTO TB_CATEGORIAS (TIPO,CATEGORIA) VALUES ( /*5*/
'Generico',
'Antibiótico '
);

INSERT INTO TB_PRODUTOS (NOME, TARJA, ANO_VALIDADE, VALOR, FK_CATEGORIAS) VALUES ( /*Inserido 8 valores nessa tabela*/
'Xarope',
'Amarelo',
2025,
50.00,
3
);

SELECT * FROM TB_PRODUTOS WHERE VALOR > 50;
SELECT * FROM TB_PRODUTOS WHERE VALOR BETWEEN 5 AND 60;
SELECT NOME FROM TB_PRODUTOS WHERE NOME LIKE '%c%';
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.FK_CATEGORIAS;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.FK_CATEGORIAS WHERE TB_CATEGORIAS.CATEGORIA = 'Anti-inflamatório';